# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedPathHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedPathHelpersModule`.


module GeneratedPathHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def admin_invoice_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_invoices_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_outbox_event_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_outbox_events_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_reconciliations_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_transfer_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_transfers_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_account_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_accounts_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_accounts_sync_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_metrics_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_reconciliations_run_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_transfer_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_transfers_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_virtual_accounts_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_invoice_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_invoice_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_proxy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_direct_uploads_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_disk_service_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_health_check_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_notes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_representation_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_proxy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_proxy_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_redirect_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_rails_disk_service_path(*args); end
end
