# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedUrlHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedUrlHelpersModule`.


module GeneratedUrlHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def admin_invoice_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_invoices_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_outbox_event_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_outbox_events_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_reconciliations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_transfer_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_transfers_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def admin_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_account_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_accounts_sync_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_accounts_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_metrics_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_reconciliations_run_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_transfer_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_transfers_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_virtual_accounts_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_admin_invoice_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_admin_invoice_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_direct_uploads_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_disk_service_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_health_check_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_notes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_representation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_redirect_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_rails_disk_service_url(*args); end
end
